Chat Prototype Code
//
//  ContentView.swift
//  ChatPrototype
//
//  Created by Eunji Lee on 11/12/24.
//

import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack(spacing:25){
            Text("Knock Knock!")
                .padding()
                .background(Color.yellow, in: RoundedRectangle(cornerRadius: 8))
                .shadow(radius: 2)
            Text("Whos there..?")
                .padding()
                .background(Color.teal, in: RoundedRectangle(cornerRadius: 8))
                .shadow(radius: 2)
        }
        .padding()
    }
}

#Preview {
    ContentView()
}

Onboarding Flow Code
//
//  FeatureCard.swift
//  OnboardingFlow
//
//  Created by Eunji Lee on 11/15/24.
//

import SwiftUI

struct FeatureCard: View {
    let iconName: String
    let description: String
    
    var body: some View{
        HStack {
            Image(systemName: iconName)
                .font(.largeTitle)
                .frame(width: 50)
                .padding(.trailing, 10)
            
            Text(description)
            
            Spacer()
        }
        .padding()
        .background(.tint,in: RoundedRectangle(cornerRadius: 12))
        .foregroundStyle(.white)
    }
}

#Preview {
    FeatureCard(iconName: "person.2.crop.square.stack.fill",
description: "A multiline descripton about a feature paired with an image on the left")
}

WeatherForecast Code ## work in progress
//
//  ContentView.swift
//  WeatherForecast
//
//  Created by Eunji Lee on 11/12/24.
//

import SwiftUI

struct ContentView: View {
    var body: some View {
        HStack{
            DayForecast(day: "Mon", isRainy: false,high: 70, low: 50)
            
            DayForecast(day: "Tue",isRainy: true, high: 60, low: 40)
        }
    }
}

#Preview {
    ContentView()
}

struct DayForecast: View {
    let day: String
    let isRainy: Bool
    let high: Int
    let low: Int
    
    var iconName: String {
        if isRainy{
            return "cloud.rain.fill"
        } else {
            return "sun.max.fill"
        }
    }
    var iconColor: Color {
        if isRainy {
            return Color.blue
        }
        else {
            return Color.yellow
        }
    }
    
    var body: some View {
        VStack {
            Text(day)
                .font(Font.headline)
            Image(systemName: iconName)
                .foregroundStyle(iconColor)
                .font(Font.largeTitle)
                .padding(5)
            Text("High: \(high)ยบ")
                .fontWeight(Font.Weight.semibold)
            Text("Low: \(low)ยบ")
                .fontWeight(Font.Weight.medium)
                .foregroundStyle(Color.secondary)
        }
        .padding()
    }
}

